### ISSUE TITLE
Detect unsupported browsers and show a friendly message

### ISSUE THREAD

**Issue by amcgee** [dhis2/app-platform#130]
TODO: A full-screen error message with buried technical details saying "AbortController is not defined" (current behavior) is not acceptable.

**Comment by amcgee** [comment]
CC @cooper-joe - zero rush on this but if you have time to mock up a simple "This browser is not supported" full-screen message that might be helpful

**Comment by cooper-joe** [comment]
Sure, will do! Do we have an established browser we would prefer the user use? I'm thinking we can provide a link to Firefox, perhaps? Or at least give a list of the browsers we do support, avoiding a guessing game for the user to fix the issue.

**Comment by amcgee** [comment]
Yeah, a list of supported browsers would probably be nice.  I *think* we recommend Chrome generally?  But definitely game for a Firefox link.  CC @varl @larshelge

**Comment by varl** [comment]
Our browserslist file is the de facto list of the browsers we support (and should be up-to-date): https://github.com/dhis2/cli-style/blob/master/config/js/browserslist.config.rc

Edge, Firefox, Chrome are all equally prioritized. I do not think that we should ever just recommend one browser.

**Comment by cooper-joe** [comment]
Here's a mockup for this. It uses the same format as the generic 'somethings gone wrong' error screen, so the design can be used.

![image](https://user-images.githubusercontent.com/33054985/74751289-52a9e400-526d-11ea-80c3-02dcf07c910d.png)

I decided not to include a link to/mention of any specific browser as we do not want to maintain or be responsible for that link/mention. 

SVG code for the icon:
```
<svg height="124" viewBox="0 0 121 124" width="121" xmlns="http://www.w3.org/2000/svg"><g fill="#a0adba" transform="translate(-.5)"><path d="m95.03 64.61c-1.2558172-2.37118-3.7192983-3.8541271-6.4025-3.8541271s-5.1466828 1.4829471-6.4025 3.8541271l-25.28 48.165c-1.1635872 2.227338-1.0724699 4.902013.24 7.045 1.3241621 2.132553 3.6547866 3.431125 6.165 3.435h50.555c2.508728-.004712 4.838271-1.300792 6.165-3.43 1.312861-2.143284 1.402115-4.818992.235-7.045zm-10.155 18.645c0-2.0710678 1.6789322-3.75 3.75-3.75s3.75 1.6789322 3.75 3.75v15c0 2.071068-1.6789322 3.75-3.75 3.75s-3.75-1.678932-3.75-3.75zm3.75 31.25c-2.7614237 0-5-2.238576-5-5s2.2385763-5 5-5 5 2.238576 5 5c-.0027595 2.759471-2.2405277 4.995001-5 4.995z"/><path d="m105.88.755h-90c-8.28427125 0-15 6.71572875-15 15v72.5c0 8.2842712 6.71572875 15 15 15h30c2.7614237 0 5-2.238576 5-5 0-2.7614237-2.2385763-5-5-5h-30c-2.7614237 0-5-2.2385763-5-5v-61.255c0-.6903559.5596441-1.25 1.25-1.25h97.5c.690356 0 1.25.5596441 1.25 1.25v31.25c0 2.7614237 2.238576 5 5 5 2.761424 0 5-2.2385763 5-5v-42.5c-.002761-8.28231856-6.717681-14.995-15-14.995zm-83.27 15c-.8509717 1.5409543-2.4721895 2.4976578-4.2325 2.4976578s-3.3815283-.9567035-4.2325-2.4976578c-.4787996-.7477058-.7433939-1.612393-.765-2.5.0270968-2.7501217 2.2498783-4.97290324 5-5 1.7546924.02023545 3.3660736.97258841 4.23 2.5.4810321.7469709.7474085 1.6118294.77 2.5-.0233572.8880452-.2896715 1.752702-.77 2.5zm17.5 0c-.8509717 1.5409543-2.4721895 2.4976578-4.2325 2.4976578s-3.3815283-.9567035-4.2325-2.4976578c-.4787996-.7477058-.7433939-1.612393-.765-2.5.0208394-.8877311.2854955-1.7526205.765-2.5.8509717-1.5409543 2.4721895-2.49765776 4.2325-2.49765776s3.3815283.95670346 4.2325 2.49765776c.4810321.7469709.7474085 1.6118294.77 2.5-.0233572.8880452-.2896715 1.752702-.77 2.5zm17.5 0c-.8509717 1.5409543-2.4721895 2.4976578-4.2325 2.4976578s-3.3815283-.9567035-4.2325-2.4976578c-.4787996-.7477058-.7433939-1.612393-.765-2.5.0208394-.8877311.2854955-1.7526205.765-2.5.8509717-1.5409543 2.4721895-2.49765776 4.2325-2.49765776s3.3815283.95670346 4.2325 2.49765776c.4810321.7469709.7474085 1.6118294.77 2.5-.0233572.8880452-.2896715 1.752702-.77 2.5z"/></g></svg>
```

**Comment by amcgee** [comment]
We should use [browserlist-useragent](https://github.com/browserslist/browserslist-useragent) and ensure we're rather lenient in our detection (with the settings `unreleased versions`, `ignore minor`, `ignore patch` and maybe even `allow higher versions`)

We'll also want to make sure we do browser agent detection *as early as possible* (delay-loading additional javascript) so that we don't crash unsupported browsers but instead show the lovely error message @cooper-joe made!

**Comment by varl** [comment]
Could we blacklist broken browsers rather than whitelist?

**Comment by amcgee** [comment]
That could be an option, but it might be harder to implement with existing tools?  Not sure.

**Comment by ismay** [comment]
> Could we blacklist broken browsers rather than whitelist?

https://github.com/browserslist/browserslist-useragent uses our .browserslistrc right? I think the format we're using now is close to the format they recommend. (Maybe I'm misunderstanding what you mean with blacklist, I assumed you meant in the browserslistrc)

By the way, we could also try to dynamically polyfill older browsers first (so the polyfills wouldn't be bundled with the app, but only loaded by older browsers) with https://polyfill.io/v3. They check the user agent and try to polyfill the browser to a modern state.

**Comment by amcgee** [comment]
Dynamic polyfills could be nice, but there are still going to be browsers we don't support (like IE) and won't polyfill.  We would need to bundle the dynamic polyfills with the application or host the service in the core since we can't use an external service, but `polyfill.io` looks interesting.

Related, but we'll need to move away from UserAgent strings when Chrome gets rid of them later this year - https://www.infoq.com/news/2020/03/chrome-phasing-user-agent/

**Comment by ismay** [comment]
> We would need to bundle the dynamic polyfills with the application or host the service in the core since we can't use an external service

Ah of course you're right, forgot about that.
