### ISSUE TITLE
JIRA epic is not public

### ISSUE THREAD

**Issue by teug91** [dhis2/app-platform#144]
The [JIRA epic](https://jira.dhis2.org/browse/TECH-179) linked from the readme is not public.

>This issue can't be viewed
>The issue you're trying to view can't be displayed.
>It may have been deleted or you don't have permission to view it right now.

**Comment by varl** [comment]
Yeah, that's a bit rude of us. The TECH project in JIRA is an internal project for issues of a technical nature which should not be incorporated in the standard development process for DHIS2. It's not open for the public at this point in time and we are still trying to figure out if it should or should not be.

**Comment by amcgee** [comment]
Just to clarify (for @teug91 and anyone finding this issue) - we're using GitHub Issues for bug and future enhancement tracking.  We will continue to use the Jira issue (in a private project) for internal project management purposes, but the canonical place for feedback, known issues, and roadmap communication will still be GitHub.

Closing this for now, let me know if you have any questions!
