### ISSUE TITLE
ESLint config not found when missing from application root

### ISSUE THREAD

**Issue by amcgee** [dhis2/app-platform#197]
And eslint plugin dependency resolution gets funky when adding a `.eslintrc.js` to `/shell`.

(Credit @awgaan)

**Comment by amcgee** [comment]
@varl this seems to be an issue when eslint plugins aren't hoisted up to `node_modules` from `@dhis2/cli-style/node_modules`?

```sh
./node_modules/.bin/d2-style js check
d2-style > javascript 
Cannot find module 'eslint-config-prettier'
Referenced from: /Users/awm/dev/dhis2/frontend/tools/platform/shell/node_modules/
@dhis2/cli-style/config/js/eslint.config.js
Referenced from: /Users/awm/dev/dhis2/frontend/tools/platform/shell/node_modules/
@dhis2/cli-style/config/js/eslint-react.config.js
Referenced from: /Users/awm/dev/dhis2/frontend/tools/platform/shell/.eslintrc.js
➜  shell git:(feat/compiler-2dot0) ✗ ./node_modules/.bin/d2-style --version
5.0.3
➜  shell git:(feat/compiler-2dot0) ✗ ls ./node_modules | grep eslint
@typescript-eslint
eslint
eslint-import-resolver-node
eslint-module-utils
eslint-plugin-react
eslint-scope
eslint-utils
eslint-visitor-keys
➜  shell git:(feat/compiler-2dot0) ✗ ls ./node_modules/@dhis2/cli-style/node_modules | grep eslint
babel-eslint
eslint
eslint-config-prettier
eslint-plugin-eslint-plugin
eslint-plugin-react
```

**Comment by varl** [comment]
Hm. Any branch I can reproduce this on?

First thing I would try is to remove ESLint 5 from the app-shell: https://github.com/dhis2/app-platform/blob/master/shell/package.json#L28 as that might cause conflicts with ESLint 6 that cli-style depends on.

The ESLint 5 => 6 upgrade changes how they resolve plugins and that sounds similar to what we are seeing here: https://eslint.org/docs/user-guide/migrating-to-6.0.0#plugins-and-shareable-configs-are-no-longer-affected-by-eslints

**Comment by amcgee** [comment]
Ah hmm, yeah that could be it.  Unfortunately I think we need to keep it in the `shell`, otherwise a platform app which doesn't have its own eslint config will fail with an "eslint config not found" error (you can repro that one by just running `d2 app scripts init test` and then `cd test && yarn build`, which is what @awgaan saw.  I ran into the resolution issue trying to add a config to the shell)

Will try with eslint 6... not sure how we want to solve the "eslint somewhere higher in the tree" issue (we pass SKIP_PREFLIGHT_CHECK to CRA to supress a warning about this)
