### ISSUE TITLE
Wrong import path for style-inject when building a library with a .css import

### ISSUE THREAD

**Issue by edoardo** [dhis2/app-platform#208]
This problem happens in DV, where the plugin build is broken.
The error I get when starting the app is the following:

>/Users/edoards@ifi.uio.no/dev/src/data-visualizer-app/packages/plugin/build/es/lib.js
Module not found: Can't resolve '../../../node_modules/style-inject/dist/style-inject.es.js' in '/Users/edoards@ifi.uio.no/dev/src/data-visualizer-app/packages/plugin/build/es'

The problem is that `style-inject` dependency is at root level, the correct path for the import is: `../../../../node_modules/style-inject/dist/style-inject.es.js`.

(In DV we have 2 packages: app and plugin, so that is different from the typical app scenario.)

This started to happen when in plugin I added a CSS import (in the same way App.js imports App.css) for the PivotPlugin.

See: https://github.com/dhis2/data-visualizer-app/blob/task/rework-options/packages/plugin/src/PivotPlugin.js#L23

**Comment by amcgee** [comment]
Thanks @edoardo - The issue is that libraries don’t (currently) support `.css` imports, since that would make assumptions about the loaders available in the parent - I think we’re heading in the direction of always using `styled-jsx` for libraries, so that the bundle is self-contained.  Could you do that here instead?

CC @varl, ref https://github.com/dhis2/notes/issues/79#issuecomment-563933328

**Comment by amcgee** [comment]
The way this manifests is quite strange, though - we should probably catch `.css` imports with an `eslint` rule or something to prevent the library build succeeding.

**Comment by edoardo** [comment]
ok, thanks @amcgee i'm going to change to `styled-jsx`.

**Comment by design1online** [comment]
I'm having this same problem. There needs to be a way to specify the import relative to the package this is installed into, not relative to the package the dist is put into.

**Comment by varl** [comment]
Superseded by: https://jira.dhis2.org/browse/LIBS-28
