### ISSUE TITLE
Bootstrapped app test file errors because there's no <DataProvider>

### ISSUE THREAD

**Issue by amcgee** [dhis2/app-platform#237]
This is a legitimate error, but the test doesn't fail.  Also, we shouldn't try to render the app without a mock provider of some kind...

<img width="858" alt="Screen Shot 2020-01-03 at 3 39 16 PM" src="https://user-images.githubusercontent.com/947888/71729124-3679f100-2e3f-11ea-87db-e75d0f7352ae.png">

**Comment by varl** [comment]
Superseded by: https://jira.dhis2.org/browse/LIBS-27
