### ISSUE TITLE
Dev server

### ISSUE THREAD

**Issue by teug91** [dhis2/app-platform#24]
Would it be possible to add an option to set the dev server manually? Sometimes when developing third party apps you need a server with some specific metadata. And when you work with multiple people it's nice to be able to connect to the same server.

This functionality is not needed for the UIO course we talked about last week. It's just something I personally (and some at HISP India) would find useful.

**Comment by amcgee** [comment]
Hi `teug91` thanks for the feedback!

To clarify, are you talking about the DHIS2 server the app points to when running `yarn start` which defaults to `localhost:8080`?  If so this IS actually configurable right now (though not documented, so it could change if we have a better solution in the future) through the environment variable `DHIS2_BASE_URL`, so you could run - for instance - `DHIS2_BASE_URL="https://my-dhis2-server.com" yarn start` and it should work.  Let me know if it doesn't or if you are talking about a different issue!

**Comment by teug91** [comment]
Can't get this to work. Both of the below approaches should work, right?

```
# [root-dir]/.env.development
DHIS2_BASE_URL=https://amrtest.icmr.org.in/amr
```

```
yarn start DHIS2_BASE_URL=https://amrtest.icmr.org.in/amr
```

It still tries to fetch from `localhost:8080`.

**Comment by Mohammer5** [comment]
@teug91 If you're talking about the example app, it's a "Create-react-app" app, which means that all env vars need to be prefixed with `REACT_APP_`, so you'd use:

`REACT_APP_DHIS2_BASE_URL=https://amrtest.icmr.org.in/amr yarn start`
(or set the variable in your `.env.development`/`.env.development.local`)

**Comment by amcgee** [comment]
@teug91 - Not quite, but almost!

1. We don't currently support .env files in the platform, though I'd like to so we probably will soon.
2. Your second approach is almost correct, but you need to switch the order.  The environment variable assignment comes before the command.  It should be:

```js
DHIS2_BASE_URL=https://amrtest.icmr.org.in/amr yarn start
```

@Mohammer5 - it's actually not create-react-app, it's app-shell, and we manage the DHIS2_BASE_URL env var in app-scripts.

**Comment by amcgee** [comment]
@teug91 you can also specify the `baseUrl` in the `d2.config.js` config file if you don't want to pass the environment variable every time.

Reference https://github.com/dhis2/app-platform/blob/master/cli/src/lib/shell/env.js.  

This needs more documentation, I'll add it today.

**Comment by teug91** [comment]
Working. Thanks!
