### ISSUE TITLE
REACT_APP_* env vars are not filtered out

### ISSUE THREAD

**Issue by Mohammer5** [dhis2/app-platform#280]
When specifying the REACT_APP_DHIS2_ENV_VAR env var, it's being used as the backend's url.

# How to reproduce

```bash
> REACT_APP_DHIS2_ENV_VAR=https://debug.dhis2.org/dev yarn start
```

**Comment by amcgee** [comment]
Should be `REACT_APP_DHIS2_BASE_URL` but confirmed that we're not properly sanitizing the env before passing to CRA

**Comment by amcgee** [comment]
Thanks @Mohammer5 !

**Comment by varl** [comment]
We require that `EXTEND_ESLINT` is passed on to CRA though, so I'm wondering if this issue implies that we should strip them out or knowingly whitelist the ones we need?

**Comment by amcgee** [comment]
`EXTEND_ESLINT` should come from [the `.env` file in `app-shell`](https://github.com/dhis2/app-platform/blob/master/shell/.env), so I think we're good there?

**Comment by varl** [comment]
Great!

**Comment by varl** [comment]
Superseded by: https://jira.dhis2.org/browse/LIBS-26
