### ISSUE TITLE
Clarify `init` installation documentation

### ISSUE THREAD

**Issue by amcgee** [dhis2/app-platform#281]
Currently the [Bootstrapping page](https://platform.dhis2.nu/#/bootstrapping) recommends running `d2 app scripts init`, but there are no instructions for installing the global DHIS2 CLI.  Thanks @Mohammer5 for the find!

**Comment by Mohammer5** [comment]
Nice, you created an issue for this!
I think it'd be good if we included commands for bootstrapping inside an existing app (with `.` as path and `--force`)

**Comment by Mohammer5** [comment]
We should also add that the entry file needs to export its component as default export (might be good to know when bootstrapping inside existing apps).
The new maintenance app exported the app component as named export and I just got an error from the app-runtime, which didn't help much (just said that a promise returned undefined)
