### ISSUE TITLE
ui-widgets doesn't need to be installed

### ISSUE THREAD

**Issue by Mohammer5** [dhis2/app-platform#282]
This is just a minor issue with the [list of provided libraries](https://platform.dhis2.nu/#/usage/dependencies).

`ui-widgets` is missing in that list. I assume this is because currently only the `HeaderBar` is available which is already provided by the app shell. But soon there will be more components, so I'd say we include that one in the list

**Comment by amcgee** [comment]
We strip out everything but the HeaderBar in the version of `ui-widgets` that we include, since it's a dependency of `app-adapter` rather than `app-shell`, we'd want to move it up to `app-shell` to be a first-class standard library and then we could update the documentation.

**Comment by amcgee** [comment]
Note (tangentially related) - if we move to using `yarn` v2 or `yarn` v1 with Plug-and-Play then our method for providing "zero-install" dependency will probably break as PnP requires that all dependencies are explicitly declared in their local `package.json`.

**Comment by Mohammer5** [comment]
`ui-core` is already a part of `app-shell`, right? Do we want to put `ui-widgets` there as well once there are more components (like the data table, the org unit tree, etc) or do we want apps to declare that dependency themselves?

**Comment by amcgee** [comment]
Just looked at the source and technically `ui-widgets` is currently included as a dep of `app-adapter`, so it's available and can be used by the app.  It should pick up non-breaking `ui-widgets` changes too.  That being said, I think we would want the app to declare their own dependency, and then `yarn` would de-duplicate them if they have overlapping version ranges.
