### ISSUE TITLE
test command doesn't accept files to limit test range

### ISSUE THREAD

**Issue by Mohammer5** [dhis2/app-platform#283]
# What is this

bug

# Description

With create-react-app I could do the following.
It ran only the specified tests in watch mode

```bash
> yarn test path/to/__tests__/file.test.js
```

When I do the same with `d2-app-scripts`, it runs all tests

**Comment by awgaan** [comment]
Temporary workaround: Run with `--watch`, `P` to filter by filename.

**Comment by ismay** [comment]
Yeah I ran into this as well. Would be nice to support this.

**Comment by amcgee** [comment]
This is actually expected to work, I think, so it's a bug.  Probably a trivial fix if someone wants to look into it!

**Comment by amcgee** [comment]
This is actually expected to work, I think, so it's a bug.  Probably a trivial fix if someone wants to look into it!

**Comment by amcgee** [comment]
Maybe we're [passing the wrong parameter](https://github.com/dhis2/app-platform/blob/master/cli/src/commands/test.js#L48) to `jest`?  I think this might just match on the test name, not path.

CRA runs the [`jest` CLI](https://jestjs.io/docs/en/cli.html#jest-regexfortestfiles) which passes along the first param, we'd need to figure out what `jest` CLI does under the hood there to translate it to the programatic version

**Comment by ismay** [comment]
> Temporary workaround: Run with `--watch`, `P` to filter by filename.

That doesn't work for me. Both the filename regex and test name regex filters don't have any matches (whichever filter I enter).

Which leads me to think that maybe something's off with the cwd? Maybe jest is looking in the wrong location for the filters/specific test runs?

**Comment by amcgee** [comment]
@ismay that could be possible, would need to look into the jest `runCLI` API options - we pass `[‘./src’]` as the second arg which is how it finds the tests, might be related

**Comment by amcgee** [comment]
Actually we probably pass an absolute root path to the src dir so cwd could be incorrect here

**Comment by ismay** [comment]
This is still an issue. Would be nice to be able to filter files.

**Comment by Mohammer5** [comment]
Still an issue

**Comment by varl** [comment]
Superseded by: https://jira.dhis2.org/browse/LIBS-25
