### ISSUE TITLE
src/setupTests.js is not being used by jest

### ISSUE THREAD

**Issue by Mohammer5** [dhis2/app-platform#284]
# What is this

bug

# Description

`src/setupTests.js` is the default location used by create-react-app to setup enzyme.
It's not being used by `d2-app-scripts`

# How to reproduce

Close the [mar-y project](https://github.com/dhis2/mar-y), install dependencies and run `yarn test`

**Comment by Mohammer5** [comment]
Can be set manually in `jest.config.js(on)`

**Comment by varl** [comment]
Yeah, we need better docs for how to set it up. I struggled with it when porting ui-core to app-scripts.
