### ISSUE TITLE
jest stubs all css modules with an empty object

### ISSUE THREAD

**Issue by Mohammer5** [dhis2/app-platform#285]
# What is this

Feature

# Description

`create-react-app` uses `identity-obj-proxy` for css modules,
currently all css modules imports are mocked with an empty object

**Comment by amcgee** [comment]
We should do [the same things as CRA](https://github.com/facebook/create-react-app/blob/4bf14fa665e748af7de41addb008e0eee39905da/packages/react-scripts/scripts/utils/createJestConfig.js#L58) in our default Jest config.

Currently it can be overridden locally by the app, but would be nice to support out-of-the-box

**Comment by Mohammer5** [comment]
I'm not sure what the actual issue was but assume this is still an issue (with very low priority it seems). Keeping this one open

**Comment by varl** [comment]
Superseded by: https://jira.dhis2.org/browse/LIBS-24
