### ISSUE TITLE
Add publish and deploy commands

### ISSUE THREAD

**Issue by amcgee** [dhis2/app-platform#330]
We should automate these operations:

* Publication to the App Hub (`d2 app scripts publish`)
* Deployment to a running DHIS2 instance (`d2 app scripts deploy`)

This is particularly important to facilitate continuous integration workflows.

**Comment by amcgee** [comment]
@varl have you already started implementing this?

**Comment by varl** [comment]
@amcgee No, I started working on the d2-ci deployment script so we can stop using Travis and move to GH Actions for applications.

**Comment by amcgee** [comment]
We've implemented `deploy` (#451) but still need to finish implementing the `publish` command

**Comment by varl** [comment]
Superseded by: https://jira.dhis2.org/browse/LIBS-22
