### ISSUE TITLE
Support additional `test` options

### ISSUE THREAD

**Issue by Mohammer5** [dhis2/app-platform#338]
## Feature or bug

Feature

## Description

NOTE: Not being able to watch/test specific files is being discussed in #283 

Some jest options I frequently use are:

* `--lastCommit`
* `--bail` This one is especially useful when working on some code and it's related test file(s). I can check whether I broke something else with `--bail 2`

It'd be nice to use them with our test command as well

**Comment by Mohammer5** [comment]
This would be especially useful in combination with `describe.only/skip` and `it.only/skip`

**Comment by amcgee** [comment]
Duplicate of #283 (and related to #269) - we don't want to blindly forward all options to `jest` but we should support test filtering (it's broken currently)

**Comment by amcgee** [comment]
I believe passing a regex as the first argument to `test` should filter the *test names*, but haven't confirmed that

**Comment by Mohammer5** [comment]
Neither `/Transfer/` not `"/Transfer/"` worked.

I don't want to "blindly forward all options to jest", I don't really care how it's done internally (e. g. through a whitelist or stripping out all custom options of our command and then forward the rest).

It'd be nice to have all options jest offers available. Some of them are really useful, potentially all could be used. What's the reasoning for not doing that?

I use `--lastCommit`, `--bail 2`, `--help`, `--expand`, `--notify` (some rarely) every now and then.

**Comment by Mohammer5** [comment]
We could discuss that in the "duplicate" issue, although the title is about documentation, not about a missing feature

**Comment by amcgee** [comment]
@Mohammer5 the specific issue of not being able to filter tests is #283, we can discuss additional features (`--lastCommit`, for instance) here.

The reason for not proxying all options to `jest` is so that we limit the API surface area and don't expose too much of the `jest` implementation detail.  This was a conscious decision early on that @varl and I made, we can revisit it if we want to expose `jest` to the user (in some ways we already do, through jest configuration options)

**Comment by Mohammer5** [comment]
Ok, fair enough. I assume the reasoning is that we want to be able to change testing libraries breaking existing implementations?

I'll update the issue's description about what I'd like to be able to do.

**Comment by Mohammer5** [comment]
Can be closed for now
