### ISSUE TITLE
Documentation improvement on App Platform Scripts page 

### ISSUE THREAD

**Issue by paschalidi** [dhis2/app-platform#353]
Hello y'all 👋 

I was going through the documentation and I found that some part of the App Platform Scripts doesn't make much sense for me. I am bringing it up so that it can be discussed if it is only me that had a little bit of trouble to understand what is going on there.

Look [here](https://github.com/dhis2/app-platform/blame/3e769977151cd48cd787b697c309e26c45930868/docs/scripts.md#L7) for the code and [here](https://platform.dhis2.nu/#/scripts) for the website. 

My suggestion would be that we explicitly make clear that the `init` command will install certain packages and one of those would be `d2-app-scripts` however if the user wants to install the package as a standalone they can do by running `yarn add --dev @dhis2/cli-app-scripts`. 

It is a very simple issue but I hope that it makes sense that we discuss it first before I open a PR. Le me know what you think and I will be happy to go on and rephrase this.

**Comment by amcgee** [comment]
Hi @paschalidi thanks for the issue - did you see the earlier documentation page `installation` which lays out these two options pretty explicitly?  If you have recommendations for how to clarify the other documentation pages, feel free to make a pull request!

**Comment by varl** [comment]
Superseded by: https://jira.dhis2.org/browse/LIBS-21
