### ISSUE TITLE
Author field in d2.config.js isn't automatically expanded

### ISSUE THREAD

**Issue by amcgee** [dhis2/app-platform#357]
The following key in `package.json` (email and url can optionally be added, [see package.json spec](https://docs.npmjs.com/files/package.json#people-fields-author-contributors)):

```
"author": "Austin McGee"
```

is correctly expanded to the following in the generated `manifest.webapp`:

```
"developer": {
    "name": "Austin McGee"
}
```

However, the same "author" key in `d2.config.js` is not expanded, remaining `"developer": "Austin McGee"`.  This is problematic because a string is not valid for the developer field in the (legacy) [manifest.webapp spec](http://mozilla.github.io/webapps-spec/#propdef-developer) and apps with a string in this field are summarily rejected by a DHIS2 instance with the terribly opaque error **App could not be installed on file system**

Proposed solution: the `author` field in `d2.config.js` should be expanded in the same manner as the `author` field in `package.json`

Thanks @chathurawidanage for catching this one!

**Comment by varl** [comment]
Superseded by: https://jira.dhis2.org/browse/LIBS-19
