### ISSUE TITLE
Consider replacing moment with a smaller date library

### ISSUE THREAD

**Issue by teug91** [dhis2/app-platform#409]
A developer from one of the HISP groups brought up `moment` being problematic due to its size. The developer had previous experience where adding `moment` as a dependency caused apps to be too slow where the network wasn't great.

As DHIS2 is often used in areas with lacking infrastructure, it may be worth considering replacing `moment` with something leaner like `dayjs`. I realize that many DHIS2 apps use `moment` at moment :smirk: so there is some work involved to get completely rid of it.

![source-map-explorer](https://user-images.githubusercontent.com/430725/83793348-b29d8c80-a69c-11ea-97de-d8900ba9d2f1.png)

**Comment by amcgee** [comment]
Thanks for bringing this up @teug91 !  Moment is pretty large, and I'd like to consider replacing it, but we need to consider all the places `moment` is used and "assumed" to exist across the ecosystem.  We have improved the bundle-size impact of `moment` someone in the platform by automatically delay-loading only the locale of the current user, which should help.  Do you know if the HISP developer was referring to the bundle-split version of Moment or the naive import of all locales?

**Comment by amcgee** [comment]
Finally, we will be re-evaluating our client-side date functions across the board as we revamp support for non-gregorian calendars, which will involve some sophisticated translations on top of a standard date library.  It might make sense to look into optimizing gregorian date manipulation at the same time.

**Comment by amcgee** [comment]
Related to this, moment development [is going into "maintenance mode"](https://momentjs.com/docs/#/-project-status/)

**Comment by varl** [comment]
Superseded by: https://jira.dhis2.org/browse/LIBS-17
