### ISSUE TITLE
Debugging: line numbers and project structure

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/app-platform#428]
When we are writing the app, we work in the `scr` folder. But the app is being served from the `.d2/shell/src/D2App` folder. That in itself can get a little confusing, because when looking in DevTools the file-path is different than the one in your editor. 

Besides that, it seems that the files from `src` aren't simply copied to the `.d2/shell/src/D2App` folder, but also some formatting is being applied. As a result, the line numbers in DevTools often don't match the line numbers in the actual source file.

It'd be nice if both things could be fixed. However, I am personally more frustrated by the second issue, and that one also seems easier to fix.

**Comment by varl** [comment]
Superseded by: https://jira.dhis2.org/browse/LIBS-15
