### ISSUE TITLE
Adding option on the `start` script to allow running the app from the same directory as the one I am editing and not from the `.d2/shell`

### ISSUE THREAD

**Issue by paschalidi** [dhis2/app-platform#452]
This is a feature request. 

As a developer while I am coding I use breakpoints and `debugger`s to debug stuff. 
This helps me particularly when I want to stop the flow of the code, inspect values etc etc. 
To better explain myself here on the breakpoints. On Webstorm that I personally use but also on VSCode you can use the IDE to add a breakpoint by simply marking a line. That means you dont have to add a line of code saying `debugger`. On the image bellow for instance the red dot is where the execution will pause and you then can inspect the values at that point.

Usually I do that quite a lot while coding. Now since the application is running from the `shell` directory after it is being complied, looks like I cant do easily the same anymore. If I wanted to do the same I would have to open the same file from the `shell` directory and add the breakpoint there, then go back to the file I am editing add few lines of code and if I would like to add another breakpoint I will have to go back to the shell file again.
Sometimes this is throws me off a bit.

The request would be to add an option on the `start` script that would allow to run the application not from the `.d2/shell` directory but straight without it being complied from the `./src`

This way I could avoid what I described above.

![image](https://user-images.githubusercontent.com/4181674/91956642-a366c300-ed0d-11ea-9d03-090e68560dec.png)

**Comment by varl** [comment]
Superseded by: https://jira.dhis2.org/browse/LIBS-14
