### ISSUE TITLE
Feature: add ability to hide the header bar

### ISSUE THREAD

**Issue by jenniferarnesen** [dhis2/app-platform#462]
Use case in dashboards: In the print mode, everything except the print area and the needed action buttons is removed/hidden from the interface to allow the user to clearly see what will be printed.

Currently, hiding the headerbar is achieved with css in the app: https://github.com/dhis2/dashboards-app/blob/master/src/components/Dashboard/Dashboard.js. Look for the `setHeaderbarVisibility` function. Also here: https://github.com/dhis2/dashboards-app/blob/master/src/components/Dashboard/styles/print.css#L1

FYI, there are other css hacks as well to achieve the printable area. See overrides for app-shell-app in this file: https://github.com/dhis2/dashboards-app/blob/master/src/components/App.css

**Comment by varl** [comment]
Superseded by: https://jira.dhis2.org/browse/LIBS-13
