### ISSUE TITLE
Platform applications break in Edge browser

### ISSUE THREAD

**Issue by amcgee** [dhis2/app-platform#63]
While this is an **edge** case, we need to officially support Edge.  We probably have to add some polyfills to make this work.

<img width="456" alt="Screenshot 2019-09-24 13 22 09" src="https://user-images.githubusercontent.com/947888/65510206-ae498e80-ded4-11e9-82b9-e952392cf25f.png">

**Comment by amcgee** [comment]
I just tried this again and can't reproduce, will keep investigating but if anyone wants to test and comment here it would be much appreciated - especially on Windows!

**Comment by awgaan** [comment]
I'll test it out Saturday as I don't have access to a Windows machine atm.

**Comment by amcgee** [comment]
Ah OK, sorry I thought you did.  No worries then!

**Comment by awgaan** [comment]
Did not manage to produce any errors on Edge either.
![image](https://user-images.githubusercontent.com/16868802/72684049-91694480-3add-11ea-8f6b-647337057fe2.png)

**Comment by amcgee** [comment]
Thanks for testing @awgaan!  I'll go ahead and close this.
