### ISSUE TITLE
Support oauth deployments

### ISSUE THREAD

**Issue by amcgee** [dhis2/app-platform#94]
Especially with `standalone` mode, it makes a lot of sense to natively support OAuth for cross-domain communication.  This requires a server component (netlify functions would to the trick) and an OAuth key-exchange (some setup or server state required to manage different keys for different remote servers) but should be pretty feasible.

**Comment by amcgee** [comment]
Ping

**Comment by varl** [comment]
Superseded by: https://jira.dhis2.org/browse/LIBS-30
